import { eq, sql } from "drizzle-orm";
import { getDb } from "@/db";
import { categories } from "@/db/schema";
import { recordAudit } from "@/lib/audit";
import { requireAdminApi } from "@/lib/auth";
import { assertInteger, cleanText, enforceSameOrigin, errorResponse, optionalText } from "@/lib/errors";
import { slugify } from "@/lib/format";

export async function POST(request: Request) { try { enforceSameOrigin(request); const admin = await requireAdminApi(); const input = await request.json() as Record<string, unknown>; const name = cleanText(input.name, "Nome", 100); const db = await getDb(); const [created] = await db.insert(categories).values({ name, slug: slugify(optionalText(input.slug, 120) ?? name), description: optionalText(input.description, 500) ?? "", imageUrl: optionalText(input.imageUrl, 500), sortOrder: Number(input.sortOrder ?? 0), active: input.active !== false }).returning(); await recordAudit(admin, request, "CATEGORY_CREATED", "Category", created.id, { name }); return Response.json({ category: created }, { status: 201 }); } catch (error) { return errorResponse(error); } }
export async function PATCH(request: Request) { try { enforceSameOrigin(request); const admin = await requireAdminApi(); const input = await request.json() as Record<string, unknown>; const id = assertInteger(input.id, "Categoria"); const db = await getDb(); await db.update(categories).set({ name: input.name ? cleanText(input.name, "Nome", 100) : undefined, slug: input.slug ? slugify(cleanText(input.slug, "Slug", 120)) : undefined, description: input.description == null ? undefined : optionalText(input.description, 500) ?? "", imageUrl: input.imageUrl == null ? undefined : optionalText(input.imageUrl, 500), sortOrder: input.sortOrder == null ? undefined : Number(input.sortOrder), active: input.active == null ? undefined : input.active === true, updatedAt: sql`CURRENT_TIMESTAMP` }).where(eq(categories.id, id)); await recordAudit(admin, request, "CATEGORY_UPDATED", "Category", id); return Response.json({ ok: true }); } catch (error) { return errorResponse(error); } }
export async function DELETE(request: Request) { try { enforceSameOrigin(request); const admin = await requireAdminApi(); const input = await request.json() as Record<string, unknown>; const id = assertInteger(input.id, "Categoria"); const db = await getDb(); await db.update(categories).set({ active: false, deletedAt: sql`CURRENT_TIMESTAMP`, updatedAt: sql`CURRENT_TIMESTAMP` }).where(eq(categories.id, id)); await recordAudit(admin, request, "CATEGORY_ARCHIVED", "Category", id); return Response.json({ ok: true }); } catch (error) { return errorResponse(error); } }
