-- ONVEX PostgreSQL schema. This file is idempotent and is executed by the
-- deploy build before the Next.js application is compiled.

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  name text NOT NULL,
  phone text,
  cpf text,
  role text NOT NULL DEFAULT 'CUSTOMER',
  active integer NOT NULL DEFAULT 1,
  email_verified_at text,
  last_login_at text,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users (email);
CREATE INDEX IF NOT EXISTS users_role_idx ON users (role);

CREATE TABLE IF NOT EXISTS categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL,
  description text NOT NULL DEFAULT '',
  image_url text,
  sort_order integer NOT NULL DEFAULT 0,
  active integer NOT NULL DEFAULT 1,
  deleted_at text,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE UNIQUE INDEX IF NOT EXISTS categories_slug_unique ON categories (slug);
CREATE INDEX IF NOT EXISTS categories_active_order_idx ON categories (active, sort_order);

CREATE TABLE IF NOT EXISTS products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id integer NOT NULL REFERENCES categories(id),
  name text NOT NULL,
  slug text NOT NULL,
  short_description text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  brand text NOT NULL DEFAULT 'ONVEX',
  base_sku text NOT NULL,
  price_cents integer NOT NULL,
  sale_price_cents integer,
  weight_grams integer NOT NULL DEFAULT 0,
  active integer NOT NULL DEFAULT 1,
  featured integer NOT NULL DEFAULT 0,
  is_new integer NOT NULL DEFAULT 0,
  sales_count integer NOT NULL DEFAULT 0,
  meta_title text,
  meta_description text,
  deleted_at text,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  CONSTRAINT products_totals_nonnegative CHECK (price_cents >= 0 AND (sale_price_cents IS NULL OR sale_price_cents >= 0))
);
CREATE UNIQUE INDEX IF NOT EXISTS products_slug_unique ON products (slug);
CREATE UNIQUE INDEX IF NOT EXISTS products_base_sku_unique ON products (base_sku);
CREATE INDEX IF NOT EXISTS products_category_active_idx ON products (category_id, active);
CREATE INDEX IF NOT EXISTS products_featured_idx ON products (featured, sales_count);

CREATE TABLE IF NOT EXISTS product_variants (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  sku text NOT NULL,
  color text NOT NULL,
  size text NOT NULL,
  stock integer NOT NULL DEFAULT 0,
  minimum_stock integer NOT NULL DEFAULT 5,
  price_adjustment_cents integer NOT NULL DEFAULT 0,
  active integer NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  CONSTRAINT product_variants_stock_nonnegative CHECK (stock >= 0),
  CONSTRAINT product_variants_minimum_nonnegative CHECK (minimum_stock >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS product_variants_sku_unique ON product_variants (sku);
CREATE UNIQUE INDEX IF NOT EXISTS product_variant_options_unique ON product_variants (product_id, color, size);
CREATE INDEX IF NOT EXISTS product_variants_product_idx ON product_variants (product_id, active);
CREATE INDEX IF NOT EXISTS product_variants_stock_idx ON product_variants (stock, minimum_stock);

CREATE TABLE IF NOT EXISTS product_images (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  storage_key text,
  url text NOT NULL,
  alt text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 0,
  is_primary integer NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS product_images_product_order_idx ON product_images (product_id, sort_order);
CREATE UNIQUE INDEX IF NOT EXISTS product_images_primary_unique ON product_images (product_id) WHERE is_primary = 1;

CREATE TABLE IF NOT EXISTS coupons (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  type text NOT NULL,
  value integer NOT NULL,
  minimum_cents integer NOT NULL DEFAULT 0,
  starts_at text,
  ends_at text,
  maximum_uses integer,
  uses_per_customer integer NOT NULL DEFAULT 1,
  current_uses integer NOT NULL DEFAULT 0,
  active integer NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE UNIQUE INDEX IF NOT EXISTS coupons_code_unique ON coupons (code);
CREATE INDEX IF NOT EXISTS coupons_active_idx ON coupons (active);

CREATE TABLE IF NOT EXISTS coupon_products (
  coupon_id integer NOT NULL REFERENCES coupons(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  PRIMARY KEY (coupon_id, product_id)
);
CREATE TABLE IF NOT EXISTS coupon_categories (
  coupon_id integer NOT NULL REFERENCES coupons(id) ON DELETE CASCADE,
  category_id integer NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  PRIMARY KEY (coupon_id, category_id)
);

CREATE TABLE IF NOT EXISTS carts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE CASCADE,
  anonymous_token text,
  coupon_id integer REFERENCES coupons(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'ACTIVE',
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS carts_user_status_idx ON carts (user_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS carts_user_active_unique ON carts (user_id) WHERE status = 'ACTIVE' AND user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS carts_anonymous_unique ON carts (anonymous_token);

CREATE TABLE IF NOT EXISTS cart_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id integer NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  variant_id integer NOT NULL REFERENCES product_variants(id),
  quantity integer NOT NULL,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  CONSTRAINT cart_items_quantity_positive CHECK (quantity > 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS cart_items_cart_variant_unique ON cart_items (cart_id, variant_id);

CREATE TABLE IF NOT EXISTS orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number text NOT NULL,
  user_id integer REFERENCES users(id) ON DELETE SET NULL,
  customer_name text NOT NULL,
  customer_email text NOT NULL,
  customer_phone text NOT NULL,
  customer_cpf text,
  subtotal_cents integer NOT NULL,
  discount_cents integer NOT NULL DEFAULT 0,
  shipping_cents integer NOT NULL DEFAULT 0,
  total_cents integer NOT NULL,
  coupon_code text,
  payment_method text NOT NULL,
  payment_status text NOT NULL DEFAULT 'PENDING',
  status text NOT NULL DEFAULT 'PENDING',
  address_snapshot text NOT NULL,
  carrier text,
  tracking_code text,
  tracking_url text,
  notes text,
  paid_at text,
  canceled_at text,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  CONSTRAINT orders_totals_nonnegative CHECK (subtotal_cents >= 0 AND discount_cents >= 0 AND shipping_cents >= 0 AND total_cents >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS orders_number_unique ON orders (order_number);
CREATE INDEX IF NOT EXISTS orders_user_date_idx ON orders (user_id, created_at);
CREATE INDEX IF NOT EXISTS orders_status_date_idx ON orders (status, created_at);

CREATE TABLE IF NOT EXISTS order_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id integer REFERENCES products(id) ON DELETE SET NULL,
  variant_id integer REFERENCES product_variants(id) ON DELETE SET NULL,
  product_name text NOT NULL,
  product_slug text NOT NULL,
  sku text NOT NULL,
  color text NOT NULL,
  size text NOT NULL,
  image_url text,
  unit_price_cents integer NOT NULL,
  quantity integer NOT NULL,
  total_cents integer NOT NULL
);
CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items (order_id);

CREATE TABLE IF NOT EXISTS order_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  type text NOT NULL,
  message text NOT NULL,
  admin_user_id integer REFERENCES users(id),
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS order_events_order_date_idx ON order_events (order_id, created_at);

CREATE TABLE IF NOT EXISTS payments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders(id),
  gateway text NOT NULL,
  gateway_payment_id text,
  method text NOT NULL,
  amount_cents integer NOT NULL,
  status text NOT NULL DEFAULT 'PENDING',
  idempotency_key text NOT NULL,
  raw_response text,
  paid_at text,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE UNIQUE INDEX IF NOT EXISTS payments_idempotency_unique ON payments (idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS payments_gateway_payment_unique ON payments (gateway_payment_id);
CREATE INDEX IF NOT EXISTS payments_order_idx ON payments (order_id);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id),
  variant_id integer NOT NULL REFERENCES product_variants(id),
  quantity_before integer NOT NULL,
  quantity_changed integer NOT NULL,
  quantity_after integer NOT NULL,
  type text NOT NULL,
  admin_user_id integer REFERENCES users(id),
  order_id integer,
  note text NOT NULL DEFAULT '',
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  CONSTRAINT inventory_final_nonnegative CHECK (quantity_after >= 0)
);
CREATE INDEX IF NOT EXISTS inventory_variant_date_idx ON inventory_movements (variant_id, created_at);
CREATE INDEX IF NOT EXISTS inventory_type_date_idx ON inventory_movements (type, created_at);

CREATE TABLE IF NOT EXISTS coupon_usages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_id integer NOT NULL REFERENCES coupons(id),
  user_id integer REFERENCES users(id),
  order_id integer NOT NULL REFERENCES orders(id),
  used_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS coupon_usages_coupon_user_idx ON coupon_usages (coupon_id, user_id);
CREATE UNIQUE INDEX IF NOT EXISTS coupon_usages_order_unique ON coupon_usages (order_id);

CREATE TABLE IF NOT EXISTS favorites (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  PRIMARY KEY (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id),
  product_id integer NOT NULL REFERENCES products(id),
  order_id integer REFERENCES orders(id),
  rating integer NOT NULL,
  comment text NOT NULL,
  status text NOT NULL DEFAULT 'PENDING',
  verified_purchase integer NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  CONSTRAINT reviews_rating_range CHECK (rating BETWEEN 1 AND 5)
);
CREATE UNIQUE INDEX IF NOT EXISTS reviews_user_product_unique ON reviews (user_id, product_id);
CREATE INDEX IF NOT EXISTS reviews_product_status_idx ON reviews (product_id, status);

CREATE TABLE IF NOT EXISTS banners (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  image_url text NOT NULL,
  link text NOT NULL DEFAULT '/loja',
  sort_order integer NOT NULL DEFAULT 0,
  active integer NOT NULL DEFAULT 1,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS banners_active_order_idx ON banners (active, sort_order);

CREATE TABLE IF NOT EXISTS store_settings (
  key text PRIMARY KEY,
  value text NOT NULL,
  updated_by integer REFERENCES users(id),
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id integer REFERENCES users(id),
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  ip text,
  data text NOT NULL DEFAULT '{}',
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS audit_admin_date_idx ON admin_audit_logs (admin_user_id, created_at);

CREATE TABLE IF NOT EXISTS webhook_events (
  event_id text PRIMARY KEY,
  provider text NOT NULL,
  payload_hash text NOT NULL,
  processed_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  token_hash text PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at text NOT NULL,
  used_at text,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE IF NOT EXISTS email_verification_tokens (
  token_hash text PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at text NOT NULL,
  used_at text,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE IF NOT EXISTS rate_limits (
  key text PRIMARY KEY,
  count integer NOT NULL DEFAULT 0,
  window_start text NOT NULL,
  CONSTRAINT rate_limits_count_nonnegative CHECK (count >= 0)
);

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  active integer NOT NULL DEFAULT 1,
  source text NOT NULL DEFAULT 'home',
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE UNIQUE INDEX IF NOT EXISTS newsletter_email_unique ON newsletter_subscribers (email);

CREATE TABLE IF NOT EXISTS contact_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  subject text NOT NULL,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'NEW',
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS contact_status_date_idx ON contact_messages (status, created_at);

CREATE TABLE IF NOT EXISTS addresses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  label text NOT NULL DEFAULT 'Principal',
  recipient_name text NOT NULL,
  postal_code text NOT NULL,
  street text NOT NULL,
  number text NOT NULL,
  complement text,
  district text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  is_default integer NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at text NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);
CREATE INDEX IF NOT EXISTS addresses_user_idx ON addresses (user_id);
