import { eq, sql } from "drizzle-orm";
import { getDb } from "@/db";
import { banners } from "@/db/schema";
import { recordAudit } from "@/lib/audit";
import { requireAdminApi } from "@/lib/auth";
import { assertInteger, cleanText, enforceSameOrigin, errorResponse, optionalText } from "@/lib/errors";
export async function POST(request:Request){try{enforceSameOrigin(request);const admin=await requireAdminApi();const input=await request.json() as Record<string,unknown>;const db=await getDb();const[created]=await db.insert(banners).values({title:cleanText(input.title,"Título",150),description:optionalText(input.description,300)??"",imageUrl:cleanText(input.imageUrl,"Imagem",500),link:optionalText(input.link,500)??"/loja",sortOrder:Number(input.sortOrder??0),active:input.active!==false}).returning();await recordAudit(admin,request,"BANNER_CREATED","Banner",created.id);return Response.json({banner:created},{status:201});}catch(error){return errorResponse(error);}}
export async function PATCH(request:Request){try{enforceSameOrigin(request);const admin=await requireAdminApi();const input=await request.json() as Record<string,unknown>;const id=assertInteger(input.id,"Banner");const db=await getDb();await db.update(banners).set({title:input.title?cleanText(input.title,"Título",150):undefined,description:input.description==null?undefined:optionalText(input.description,300)??"",imageUrl:input.imageUrl?cleanText(input.imageUrl,"Imagem",500):undefined,link:input.link==null?undefined:optionalText(input.link,500)??"/loja",sortOrder:input.sortOrder==null?undefined:Number(input.sortOrder),active:input.active==null?undefined:input.active===true,updatedAt:sql`CURRENT_TIMESTAMP`}).where(eq(banners.id,id));await recordAudit(admin,request,"BANNER_UPDATED","Banner",id);return Response.json({ok:true});}catch(error){return errorResponse(error);}}
export async function DELETE(request:Request){try{enforceSameOrigin(request);const admin=await requireAdminApi();const input=await request.json() as Record<string,unknown>;const id=assertInteger(input.id,"Banner");const db=await getDb();await db.delete(banners).where(eq(banners.id,id));await recordAudit(admin,request,"BANNER_DELETED","Banner",id);return Response.json({ok:true});}catch(error){return errorResponse(error);}}

